import { powerToDamage, accuracyToRPG, ppToRPG } from './utils.js';
import { abilitiesData } from './abilities.js';
import { initAuthUI } from './auth.js';
import { getCreatedPokemonById, getProfile, saveCreatedPokemon } from './storage.js';

const $ = (id) => document.getElementById(id);
const TYPE_COLORS = { normal:'#a8a878', fire:'#f08030', water:'#6890f0', electric:'#f8d030', grass:'#78c850', ice:'#98d8d8', fighting:'#c03028', poison:'#a040a0', ground:'#e0c068', flying:'#a890f0', psychic:'#f85888', bug:'#a8b820', rock:'#b8a038', ghost:'#705898', dragon:'#7038f8', dark:'#705848', steel:'#b8b8d0', fairy:'#ee99ac' };
const TYPE_BLOCK_ICON = { bug:'bug Type.png', steel:'Steel.png' };
const NATURES = [["Hardy",null,null,"Estoica","Neutra"],["Lonely","atk","def","Desesperada","Gosta de Picante e não gosta de Azedo"],["Brave","atk","spd","Travessa","Gosta de Picante e não gosta de Doce"],["Adamant","atk","spatk","Solitária","Gosta de Picante e não gosta de Seco"],["Naughty","atk","spdef","Firme","Gosta de Picante e não gosta de Amargo"],["Bold","def","atk","Ousada","Gosta de Azedo e não gosta de Picante"],["Docile",null,null,"Dócil","Neutra"],["Relaxed","def","spd","Relaxada","Gosta de Azedo e não gosta de Doce"],["Impish","def","spatk","Orgulhosa","Gosta de Azedo e não gosta de Seco"],["Lax","def","spdef","Excêntrica","Gosta de Azedo e não gosta de Amargo"],["Timid","spd","atk","Medrosa","Gosta de Doce e não gosta de Picante"],["Hasty","spd","def","Apressada","Gosta de Doce e não gosta de Azedo"],["Serious",null,null,"Séria","Neutra"],["Jolly","spd","spatk","Alegre","Gosta de Doce e não gosta de Seco"],["Naive","spd","spdef","Ingênua","Gosta de Doce e não gosta de Amargo"],["Modest","spatk","atk","Tímida","Gosta de Seco e não gosta de Picante"],["Mild","spatk","def","Modesta","Gosta de Seco e não gosta de Azedo"],["Quiet","spatk","spd","Quieta","Gosta de Seco e não gosta de Doce"],["Bashful",null,null,"Comedida","Neutra"],["Rash","spatk","spdef","Amável","Gosta de Seco e não gosta de Amargo"],["Calm","spdef","atk","Enjoada","Gosta de Amargo e não gosta de Picante"],["Gentle","spdef","def","Calma","Gosta de Amargo e não gosta de Azedo"],["Sassy","spdef","spd","Atrevida","Gosta de Amargo e não gosta de Doce"],["Careful","spdef","spatk","Gentil","Gosta de Amargo e não gosta de Seco"],["Quirky",null,null,"Chata","Neutra"]].map(([name,plus,minus,pt,taste])=>({name,plus,minus,pt,taste}));
const XP_TABLE = {1:0,2:10,3:20,4:30,5:40,6:50,7:60,8:70,9:80,10:90,11:110,12:135,13:160,14:190,15:220,16:250,17:285,18:320,19:360,20:400,21:460,22:530,23:600,24:670,25:745,26:820,27:900,28:990,29:1075,30:1165,31:1260,32:1355,33:1455,34:1555,35:1660,36:1770,37:1880,38:1995,39:2110,40:2230,41:2355,42:2480,43:2610,44:2740,45:2875,46:3015,47:3155,48:3300,49:3445,50:3645,51:3850,52:4060,53:4270,54:4485,55:4705,56:4930,57:5160,58:5390,59:5625,60:5865,61:6110,62:6360,63:6610,64:6865,65:7125,66:7390,67:7660,68:7925,69:8205,70:8485,71:8770,72:9060,73:9350,74:9645,75:9945,76:10250,77:10560,78:10870,79:11185,80:11505,81:11910,82:12320,83:12735,84:13155,85:13580,86:14010,87:14445,88:14885,89:15330,90:15780,91:16235,92:16695,93:17160,94:17630,95:18105,96:18585,97:19070,98:19560,99:20055,100:20555};
const state = {mode:'wild',index:[],pokemon:null,species:null,moves:{level:[],tm:[]},selectedMoves:[],abilitySelection:[],loyalty:0,gender:null,shiny:false,alpha:false,pokeball:'pokeball',xp:0,muffins:0,customImage:null,crop:{zoom:1,x:0,y:0},baseRadar:null,contestRadar:null};

const format = (n)=>n.split('-').map((v)=>v[0].toUpperCase()+v.slice(1)).join(' ');
const statMap = {hp:'hp',attack:'atk',defense:'def','special-attack':'spatk','special-defense':'spdef',speed:'spd'};

function setupMenu(){const btn=$('logoMenuBtn'),m=$('sideMenu'),b=$('sideMenuBackdrop');btn.onclick=()=>{m.classList.add('open');b.classList.remove('hidden')};b.onclick=()=>{m.classList.remove('open');b.classList.add('hidden')}}
function level(){return Number(state.mode==='wild' ? $('levelInputWild').value:$('levelInput').value)||1}
function xpToLevel(xp){let lv=1;for(let i=1;i<=100;i++){if(xp>=XP_TABLE[i]) lv=i;}return lv}
function setLevel(newLv){if(state.mode==='wild') $('levelInputWild').value=newLv; else $('levelInput').value=newLv;}
function initNatures(){const grouped=[...NATURES].sort((a,b)=>(a.plus||'zzz').localeCompare(b.plus||'zzz'));$('natureSelect').innerHTML=grouped.map((n)=>`<option value="${n.name}">${n.pt}${n.plus?` | +2 ${n.plus} / -2 ${n.minus}`:''}</option>`).join('')}
function activeNature(){return NATURES.find((n)=>n.name===$('natureSelect').value) || NATURES[0]}

async function fetchIndex(){const r=await fetch('https://pokeapi.co/api/v2/pokemon?limit=1025').then(r=>r.json());state.index=r.results.map((p,i)=>({id:i+1,name:p.name}))}
function setupSearch(){const input=$('speciesSearch');input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();const out=state.index.filter((p)=>p.name.includes(q)||String(p.id).startsWith(q)).slice(0,15);$('speciesPreview').innerHTML=out.map((p)=>`<button class="preview-item" data-id="${p.id}"><img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.id}.png" alt=""><span>#${String(p.id).padStart(4,'0')} ${format(p.name)}</span></button>`).join('');$('speciesPreview').querySelectorAll('.preview-item').forEach((b)=>b.onclick=()=>loadSpecies(b.dataset.id));});$('speciesSearchBtn').onclick=()=>loadSpecies(input.value.trim().toLowerCase())}

async function loadSpecies(idOrName){if(!idOrName)return;state.pokemon=await fetch(`https://pokeapi.co/api/v2/pokemon/${idOrName}`).then(r=>r.json());state.species=await fetch(state.pokemon.species.url).then(r=>r.json());state.xp = XP_TABLE[level()];await buildMoves();renderDetailControls();renderAbilities();renderMoves();renderSheet();const id=new URLSearchParams(location.search).get('id');if(id){const saved=getCreatedPokemonById(id);if(saved){Object.assign(state,saved.data);setLevel(saved.data.level);$('nicknameInput').value=saved.data.nickname||'';renderSheet();}}
}
async function buildMoves(){state.moves.level=[];state.moves.tm=[];for(const item of state.pokemon.moves){const vg=item.version_group_details.find((v)=>['scarlet-violet','sword-shield','ultra-sun-ultra-moon'].includes(v.version_group.name));if(!vg) continue;const model={name:item.move.name,url:item.move.url,level:vg.level_learned_at,method:vg.move_learn_method.name};if(vg.move_learn_method.name==='level-up') state.moves.level.push(model);else state.moves.tm.push(model)}state.moves.level.sort((a,b)=>a.level-b.level)}

function renderDetailControls(){ $('sheetEmpty').hidden=true; $('sheetContent').hidden=false; $('detailsBlock').hidden=false; $('natureBlock').hidden=false; $('movesSection').hidden=false; const trained=state.mode==='trained'; $('trainedRow1').hidden=!trained; $('trainedRow2').hidden=!trained; $('wildRow1').hidden=trained; $('ballBlock').hidden=!trained; $('xpControls').hidden=!trained; renderLoyalty(); renderGenderBtn(); renderPokeballs(); }
function renderLoyalty(){const c=$('loyaltyBlocks');c.innerHTML='';for(let i=1;i<=4;i++){const b=document.createElement('button');b.textContent=i<=state.loyalty?'■':'□';b.onclick=()=>{state.loyalty=i;renderLoyalty();renderSheet()};c.appendChild(b);} }
function renderGenderBtn(){ if(state.species?.gender_rate===-1){$('genderDropdownBtn').textContent='Gênero: assexual';return;} $('genderDropdownBtn').textContent=`Gênero: ${state.gender? (state.gender==='male'?'Masculino':'Feminino'):'—'}`;}
function setupGenderModal(){ $('genderDropdownBtn').onclick=()=>{if(state.species?.gender_rate===-1)return; $('genderOptions').innerHTML=`<button class="user-menu-link" id="gMale"><img src="assets/icons/male.png" width="16"> Masculino</button><button class="user-menu-link" id="gFem"><img src="assets/icons/female.png" width="16"> Feminino</button>`;$('genderModal').showModal();$('gMale').onclick=()=>{state.gender='male';$('genderModal').close();renderGenderBtn();renderSheet()};$('gFem').onclick=()=>{state.gender='female';$('genderModal').close();renderGenderBtn();renderSheet()};}; }
function renderPokeballs(){const list=['pokeball','greatball','ultraball','premierball','luxuryball'];$('pokeballGrid').innerHTML=list.map((n)=>`<button type="button" class="ball-btn ${state.pokeball===n?'active':''}" data-ball="${n}"><img src="assets/pokeball/${n}.png" onerror="this.style.display='none'" alt="${n}"><small>${n}</small></button>`).join('');$('pokeballGrid').querySelectorAll('.ball-btn').forEach((b)=>b.onclick=()=>{state.pokeball=b.dataset.ball;renderPokeballs();renderSheet()});}

function setupModes(){document.querySelectorAll('.mode-btn').forEach((btn)=>btn.onclick=()=>{state.mode=btn.dataset.mode;document.querySelectorAll('.mode-btn').forEach((b)=>b.classList.toggle('active',b===btn));$('quickControls').hidden=state.mode!=='quick';if(state.pokemon) renderDetailControls();renderSheet()})}
function setupToggles(){$('shinyToggle').onclick=()=>{state.shiny=!state.shiny;$('shinyToggle').classList.toggle('active',state.shiny);renderSheet()};$('alphaToggle').onclick=()=>{state.alpha=!state.alpha;$('alphaToggle').classList.toggle('active',state.alpha);renderSheet()}}

async function renderAbilities(){const body=$('abilitiesModalBody');const limit=level()>=40?2:1;const list=state.pokemon.abilities.map((a)=>({key:a.ability.name,isHidden:a.is_hidden,info:abilitiesData[a.ability.name]||{ptName:format(a.ability.name),name:format(a.ability.name),activation:'—',effect:'—'}}));body.innerHTML=(limit>1?'<p>Seu nível permite selecionar uma segunda habilidade.</p>':'')+list.map((a)=>`<article class="ability-option ${a.isHidden?'hidden':''} ${state.abilitySelection[0]===a.key?'sel1':''} ${state.abilitySelection[1]===a.key?'sel2':''}" data-ability="${a.key}"><strong>${a.info.ptName} (${a.info.name}) ${a.isHidden?'(oculta)':''}</strong><p>Ativação: ${a.info.activation}</p><p>${a.info.effect}</p></article>`).join('');body.querySelectorAll('.ability-option').forEach((el)=>el.onclick=()=>{const k=el.dataset.ability;if(!state.abilitySelection[0]||state.abilitySelection[0]===k) state.abilitySelection[0]=k; else if(limit>1 && (!state.abilitySelection[1]||state.abilitySelection[1]===k)) state.abilitySelection[1]=k; else state.abilitySelection=[k];renderAbilities();renderSheet()});$('openAbilitiesModalBtn').onclick=()=>$('abilitiesModal').showModal()}

function moveCard(m){const t=m.type||'normal';const c=TYPE_COLORS[t]||'#999';return `<button class="move-item" data-move="${m.name}" style="background:${c}22;border-color:${c}88"><strong>${m.pt||format(m.name)}</strong><small>${format(t)}</small></button>`}
async function enrichMove(entry){const raw=await fetch(entry.url).then(r=>r.json());const pt=raw.names.find((n)=>n.language.name==='pt-br')?.name||format(raw.name);const effect=raw.effect_entries.find((e)=>e.language.name==='pt-br')?.effect||raw.effect_entries.find((e)=>e.language.name==='en')?.effect||'Sem descrição';return {...entry,pt,type:raw.type.name,cat:raw.damage_class.name,power:raw.power,pp:raw.pp,acc:raw.accuracy,effect:effect.replace(/\$effect_chance/g,String(raw.effect_chance||''))};}
async function renderMoves(){const lv=state.moves.level.filter((m)=>m.level<=level()).slice(-24);const tm=state.moves.tm.slice(0,24);const ldetail=await Promise.all(lv.map(enrichMove));const tdetail=await Promise.all(tm.map(enrichMove));$('levelMovesList').innerHTML=ldetail.map(moveCard).join('');$('tmMovesList').innerHTML=tdetail.map(moveCard).join('');document.querySelectorAll('.move-item').forEach((b)=>b.onclick=()=>{const list=[...ldetail,...tdetail];const move=list.find((m)=>m.name===b.dataset.move);if(!move)return;if(!state.selectedMoves.includes(move.name)){if(state.selectedMoves.length>=8)state.selectedMoves.shift();state.selectedMoves.push(move.name);}openMoveModal(move);renderSheet();});}

function typeBlockPath(type){return `assets/types block/${TYPE_BLOCK_ICON[type]||`${type}.png`}`}
async function renderRelations(){const rel=await Promise.all(state.pokemon.types.map((t)=>fetch(t.type.url).then(r=>r.json())));const map={double_damage_from:new Set(),half_damage_from:new Set(),no_damage_from:new Set()};rel.forEach((r)=>Object.keys(map).forEach((k)=>r.damage_relations[k].forEach((x)=>map[k].add(x.name))));const render=(id,set)=>$(id).innerHTML=[...set].map((t)=>`<img src="${typeBlockPath(t)}" alt="${t}">`).join('')||'—';render('weaknesses',map.double_damage_from);render('resistances',map.half_damage_from);render('immunities',map.no_damage_from)}
function calcStats(){const base={};state.pokemon.stats.forEach((s)=>base[statMap[s.stat.name]]=Math.floor(s.base_stat/10)+(s.base_stat%10>=9?1:0));const lvl=level();const points=Math.floor(lvl/3);const gains={hp:0,atk:0,def:0,spatk:0,spdef:0,spd:0};const n=activeNature();if(state.mode==='wild'){const total=Object.values(base).reduce((a,b)=>a+b,0);Object.keys(base).forEach((k)=>gains[k]=Math.round((base[k]/total)*points));} else {Object.keys(base).forEach((k)=>gains[k]=Math.floor(points/6)); if(n.plus) gains[n.plus]+=2; if(n.minus) gains[n.minus]-=2;}
const final={};Object.keys(base).forEach((k)=>final[k]=Math.max(1,base[k]+gains[k]));return {base,gains,final};}
function captureChance(){if(state.mode!=='wild')return null;let c=100-level()/2;const hpPct=100;if(hpPct>51)c-=30;const evoPenalty=state.species.evolves_from_species? -10:10; c+=evoPenalty; if(state.shiny)c-=10; if(state.alpha)c-=20; if(state.species.is_legendary)c-=30; return Math.max(0,Math.round(c));}

function renderSheet(){if(!state.pokemon)return;const lvl=level();const stats=calcStats();const primary=state.pokemon.types[0].type.name;$('spriteWrap').style.borderColor=TYPE_COLORS[primary]||'#7bdc65';const displayName=state.mode==='trained' && $('nicknameInput').value.trim()?$('nicknameInput').value.trim():format(state.pokemon.name);$('sheetSprite').src=state.customImage||state.pokemon.sprites.other['official-artwork'].front_default||state.pokemon.sprites.front_default;$('sheetSprite').style.transform=`translate(${state.crop.x}px,${state.crop.y}px) scale(${state.crop.zoom})`; $('sheetDex').textContent=`#${String(state.pokemon.id).padStart(4,'0')}`;$('sheetName').textContent=displayName;$('speciesSubname').textContent=displayName!==format(state.pokemon.name)?`Espécie: ${format(state.pokemon.name)}`:'';$('sheetLevel').textContent=`Nv.${lvl}`;$('sheetTypes').innerHTML=state.pokemon.types.map((t)=>`<img src="${typeBlockPath(t.type.name)}" alt="${t.type.name}">`).join('');$('sheetShinyIcon').hidden=!state.shiny;$('sheetAlphaIcon').hidden=!state.alpha;$('sheetBallIcon').hidden=state.mode!=='trained';$('sheetBallIcon').src=`assets/pokeball/${state.pokeball}.png`;
  const hp=stats.final.hp*10;$('hpTotalFill').style.width='100%';$('hpTotalText').textContent=`${hp}/${hp}`;$('hpQuickFill').style.width='100%';$('hpQuickText').textContent=`${Math.ceil(hp/2)}/${Math.ceil(hp/2)}`;
  $('capacities').innerHTML=['INTELIGÊNCIA','FORÇA','DESLOCAMENTO'].map((n)=>`<div class="capacity"><strong>${n}</strong><div>${Math.max(1,Math.floor((stats.final.spatk+stats.final.spdef)/2))}</div></div>`).join('');
  const rows=['hp','atk','def','spatk','spdef','spd'];$('statsCompact').innerHTML=rows.map((k)=>`<div class="cell"><strong>${k.toUpperCase()}</strong><div>Basal ${stats.base[k]} | Pontos ${stats.gains[k]} | Final ${stats.final[k]}</div></div>`).join('');
  $('selectedMovesOutput').innerHTML=state.selectedMoves.map((n)=>`<button class="sel-move" data-move="${n}">${format(n)}</button>`).join('');
  document.querySelectorAll('.sel-move').forEach((b)=>b.onclick=async()=>{const e=[...state.moves.level,...state.moves.tm].find((m)=>m.name===b.dataset.move);if(e)openMoveModal(await enrichMove(e));});
  const nextLv=Math.min(100,lvl+1);const low=XP_TABLE[lvl]||0,high=XP_TABLE[nextLv]||XP_TABLE[100];const percent=high===low?100:Math.min(100,((state.xp-low)/(high-low))*100);$('xpFill').style.width=`${percent}%`;$('xpText').textContent=`XP ${state.xp} / Próx. nível ${high}`;
  $('infoTab').hidden=false;$('infoTab').innerHTML=`<h4>Aba de informações</h4><p>Proporções: ${state.pokemon.height/10}m | ${state.pokemon.weight/10}kg</p><p>Reprodução: ${state.species.gender_rate===-1?'assexual':(state.gender||'—')} | ${(state.species.egg_groups[0]?.name||'—')} ${state.species.egg_groups[1]?`| ${state.species.egg_groups[1].name}`:''}</p><p>Natureza: ${activeNature().pt} (${activeNature().taste})</p><p>Modo: ${state.mode==='wild'?'Selvagem':state.mode==='trained'?'Adestrado':'Geração'}</p>${state.mode==='wild'?`<p>Chance de captura: ${captureChance()}%</p><p>Xp dado: ${lvl}</p>`:''}${state.mode==='trained'?`<p>Lealdade: ${'■'.repeat(state.loyalty)}${'□'.repeat(4-state.loyalty)}</p>`:''}`;
  renderRelations(); renderRadars(stats.final);
}

function renderRadars(finalStats){ if(typeof Chart==='undefined') return; const labels=['HP','ATK','DEF','Sp.ATK','Sp.DEF','SPD']; const values=[finalStats.hp,finalStats.atk,finalStats.def,finalStats.spatk,finalStats.spdef,finalStats.spd]; state.baseRadar?.destroy(); state.baseRadar=new Chart($('statsRadar'),{type:'radar',data:{labels,datasets:[{data:values,backgroundColor:'rgba(123,220,101,.2)',borderColor:'#7bdc65'}]},options:{plugins:{legend:{display:false}}}}); $('radarNumbers').innerHTML=labels.map((l,i)=>`<span>${l}: ${values[i]}</span>`).join(' • ');
  const muffins=Math.min(5,Math.floor(level()/5)); if(state.muffins>muffins)state.muffins=muffins; const contest=values.map((v)=>Math.min(3,Math.floor(v/10))); contest[0]+=state.muffins; state.contestRadar?.destroy(); state.contestRadar=new Chart($('contestRadar'),{type:'radar',data:{labels:['Beleza','Fofura','Estilo','Inteligência','Vigor','Ritmo'],datasets:[{data:contest,backgroundColor:'rgba(255,105,180,.2)',borderColor:'#ff69b4'}]},options:{plugins:{legend:{display:false}}}}); $('contestNumbers').innerHTML=contest.join(' | '); $('muffinBox').innerHTML=`<p>Muffins disponíveis: ${muffins}</p><button id="muffinMinus" type="button">-</button> <strong>${state.muffins}</strong> <button id="muffinPlus" type="button">+</button>`; $('muffinPlus').onclick=()=>{if(state.muffins<muffins){state.muffins++;renderSheet();$('contestRadarModal').showModal();}}; $('muffinMinus').onclick=()=>{if(state.muffins>0){state.muffins--;renderSheet();$('contestRadarModal').showModal();}}; }

function moveTypeIcon(type){return `assets/types/${type}.png`}
function catIcon(c){return `assets/icons/${c}.png`}
async function translate(text){if(!text) return 'Sem descrição'; const p=text.replace(/\n|\f/g,' '); try{const r=await fetch(`https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=pt&dt=t&q=${encodeURIComponent(p)}`);const d=await r.json();return d[0].map((c)=>c[0]).join('');}catch{return p;}}
async function openMoveModal(move){$('moveModalTitle').textContent=move.pt||format(move.name);$('moveModalHeader').style.borderColor=TYPE_COLORS[move.type]||'#7bdc65';$('moveDetailsBody').innerHTML=`<div class="move-modal-type"><img src="${moveTypeIcon(move.type)}" alt="${move.type}"><strong>${format(move.type)}</strong><img src="${catIcon(move.cat)}" alt="${move.cat}"></div><p>Dano RPG: <strong>${powerToDamage(move.power)}</strong></p><p>ACC RPG: ${accuracyToRPG(move.acc||0)} | PP RPG: ${ppToRPG(move.pp||0)}</p><section><h4>Descrição</h4><p class="move-modal-desc">${await translate(move.effect)}</p></section>`;$('moveDetailsModal').showModal();}

function setupActions(){document.querySelectorAll('[data-close-modal]').forEach((b)=>b.onclick=()=>$(b.dataset.closeModal).close());$('natureSelect').onchange=renderSheet;$('levelInput').oninput=()=>{state.xp=Math.max(state.xp,XP_TABLE[level()]);renderMoves();renderAbilities();renderSheet()};$('levelInputWild').oninput=renderSheet;$('quickGenerateBtn').onclick=async()=>{const p=state.index[Math.floor(Math.random()*state.index.length)];await loadSpecies(p.id);state.mode='quick';setLevel(Math.floor(Math.random()*100)+1);state.shiny=Math.random()>.9;state.alpha=Math.random()>.85;renderSheet();};$('openBaseRadarBtn').onclick=()=>$('baseRadarModal').showModal();$('openContestRadarBtn').onclick=()=>$('contestRadarModal').showModal();$('addXpBtn').onclick=()=>{const gain=Number($('xpInput').value||0);if(gain<=0)return;const before=level();state.xp+=gain;const after=xpToLevel(state.xp);if(after>before){setLevel(after);alert(`Subiu para nível ${after}! Ganhou pontos de atributo e pode aprender novos golpes.`);}renderMoves();renderAbilities();renderSheet();};$('copySheetBtn').onclick=()=>navigator.clipboard.writeText(`${$('sheetName').textContent} ${$('sheetLevel').textContent}`);$('copyMovesBtn').onclick=()=>navigator.clipboard.writeText(state.selectedMoves.map(format).join('\n'));
  $('savePokemonBtn').onclick=()=>{const profile=getProfile();if(!profile)return alert('Faça login para salvar.');const rec=saveCreatedPokemon({profileNick:profile.nick,data:{...state,level:level(),nickname:$('nicknameInput').value}});alert(`Salvo com ID ${rec.id}`);};
  $('spriteWrap').onclick=()=>{if(state.mode==='trained')$('imageCropModal').showModal();};
  $('customImageInput').onchange=()=>{const f=$('customImageInput').files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.customImage=r.result;$('cropPreviewImg').src=String(r.result);$('cropPreviewImg').style.transform='translate(0,0) scale(1)';};r.readAsDataURL(f)};
  ['cropZoom','cropX','cropY'].forEach((id)=>$(id).oninput=()=>{$('cropPreviewImg').style.transform=`translate(${$('cropX').value}px,${$('cropY').value}px) scale(${$('cropZoom').value})`;});
  $('saveCropBtn').onclick=()=>{state.crop={zoom:Number($('cropZoom').value),x:Number($('cropX').value),y:Number($('cropY').value)};$('imageCropModal').close();renderSheet();};
}

async function init(){setupMenu();initAuthUI({linksProvider:()=>({creation:'creation.html',created:'created-pokemons.html'})});setupModes();setupSearch();setupToggles();initNatures();setupGenderModal();setupActions();await fetchIndex();const qs=new URLSearchParams(location.search);if(qs.get('id')){const saved=getCreatedPokemonById(qs.get('id'));if(saved){await loadSpecies(saved.data.pokemon.id || saved.data.pokemon?.name || saved.data.pokemonName || 1);}}}
init();
