import { powerToDamage, accuracyToRPG, ppToRPG } from "./utils.js";
import { abilitiesData } from "./abilities.js";
import { initAuthUI } from "./auth.js";
import { getProfile, saveCreatedPokemon, getCreatedPokemonById } from "./storage.js";

const STAT_KEYS = ["hp", "atk", "def", "spatk", "spdef", "spd"];
const STAT_LABELS = { hp: "Saúde", atk: "Ataque", def: "Defesa", spatk: "Sp.Atk", spdef: "Sp.Def", spd: "Velocidade" };
const VERSION_PRIORITY = ["scarlet-violet", "sword-shield", "ultra-sun-ultra-moon", "sun-moon"];
const POKEBALLS = ["Poké Ball", "Great Ball", "Ultra Ball", "Premier Ball", "Luxury Ball", "Timer Ball"];
const XP_TABLE = {1:0,2:10,3:20,4:30,5:40,6:50,7:60,8:70,9:80,10:90,11:110,12:135,13:160,14:190,15:220,16:250,17:285,18:320,19:360,20:400,21:460,22:530,23:600,24:670,25:745,26:820,27:900,28:990,29:1075,30:1165,31:1260,32:1355,33:1455,34:1555,35:1660,36:1770,37:1880,38:1995,39:2110,40:2230,41:2355,42:2480,43:2610,44:2740,45:2875,46:3015,47:3155,48:3300,49:3445,50:3645,51:3850,52:4060,53:4270,54:4485,55:4705,56:4930,57:5160,58:5390,59:5625,60:5865,61:6110,62:6360,63:6610,64:6865,65:7125,66:7390,67:7660,68:7925,69:8205,70:8485,71:8770,72:9060,73:9350,74:9645,75:9945,76:10250,77:10560,78:10870,79:11185,80:11505,81:11910,82:12320,83:12735,84:13155,85:13580,86:14010,87:14445,88:14885,89:15330,90:15780,91:16235,92:16695,93:17160,94:17630,95:18105,96:18585,97:19070,98:19560,99:20055,100:20555};
const NATURES = [["Hardy",null,null,"Estoica","Neutra"],["Lonely","atk","def","Desesperada","Gosta de Picante e não gosta de Azedo"],["Brave","atk","spd","Travessa","Gosta de Picante e não gosta de Doce"],["Adamant","atk","spatk","Solitária","Gosta de Picante e não gosta de Seco"],["Naughty","atk","spdef","Firme","Gosta de Picante e não gosta de Amargo"],["Bold","def","atk","Ousada","Gosta de Azedo e não gosta de Picante"],["Docile",null,null,"Dócil","Neutra"],["Relaxed","def","spd","Relaxada","Gosta de Azedo e não gosta de Doce"],["Impish","def","spatk","Orgulhosa","Gosta de Azedo e não gosta de Seco"],["Lax","def","spdef","Excêntrica","Gosta de Azedo e não gosta de Amargo"],["Timid","spd","atk","Medrosa","Gosta de Doce e não gosta de Picante"],["Hasty","spd","def","Apressada","Gosta de Doce e não gosta de Azedo"],["Serious",null,null,"Séria","Neutra"],["Jolly","spd","spatk","Alegre","Gosta de Doce e não gosta de Seco"],["Naive","spd","spdef","Ingênua","Gosta de Doce e não gosta de Amargo"],["Modest","spatk","atk","Tímida","Gosta de Seco e não gosta de Picante"],["Mild","spatk","def","Modesta","Gosta de Seco e não gosta de Azedo"],["Quiet","spatk","spd","Quieta","Gosta de Seco e não gosta de Doce"],["Bashful",null,null,"Comedida","Neutra"],["Rash","spatk","spdef","Amável","Gosta de Seco e não gosta de Amargo"],["Calm","spdef","atk","Enjoada","Gosta de Amargo e não gosta de Picante"],["Gentle","spdef","def","Calma","Gosta de Amargo e não gosta de Azedo"],["Sassy","spdef","spd","Atrevida","Gosta de Amargo e não gosta de Doce"],["Careful","spdef","spatk","Gentil","Gosta de Amargo e não gosta de Seco"],["Quirky",null,null,"Chata","Neutra"]].map(([name,plus,minus,pt,taste])=>({name,plus,minus,pt,taste})).sort((a,b)=>(a.plus||"zzz").localeCompare(b.plus||"zzz"));

const $ = (id) => document.getElementById(id);
const state = { mode:"wild", pokemonIndex:[], pokemon:null, species:null, movesByLevel:[], movesByOther:[], moveCache:new Map(), selectedLevel:[], selectedOther:[], selectedAbilities:[], selectedGender:"", loyalty:0, shiny:false, alpha:false, nature:NATURES[0], xp:0, selectedBall:"", movesPt:[], muffins:0, imageCrop:{zoom:100,x:50,y:50,src:""} };
const formatName = (v) => v.split("-").map((x)=>x[0].toUpperCase()+x.slice(1)).join(" ");
const convertStat = (v) => (v % 10 >= 9 ? Math.floor(v / 10) + 1 : Math.floor(v / 10));

function setupMenu(){const b=$("logoMenuBtn"),m=$("sideMenu"),bd=$("sideMenuBackdrop");b?.addEventListener("click",()=>{m?.classList.add("open");bd?.classList.remove("hidden");});bd?.addEventListener("click",()=>{m?.classList.remove("open");bd?.classList.add("hidden");});}

async function fetchIndex(){const r=await fetch("https://pokeapi.co/api/v2/pokemon?limit=1025").then(x=>x.json());state.pokemonIndex=r.results.map((p,i)=>({id:i+1,name:p.name}));}
function setupModes(){document.querySelectorAll(".mode-btn").forEach((btn)=>btn.addEventListener("click",()=>{state.mode=btn.dataset.mode;document.querySelectorAll(".mode-btn").forEach((x)=>x.classList.toggle("active",x===btn));$("generationControls").hidden=state.mode!=="generation";$("nicknameWrap").hidden=state.mode==="wild";$("loyaltyWrap").hidden=state.mode==="wild";$("ballWrap").hidden=state.mode!=="trained";$("xpControls").hidden=state.mode!=="trained";render();}));}
function setupSearch(){const input=$("speciesSearch");input.addEventListener("input",updatePreview);$("speciesSearchBtn").addEventListener("click",()=>loadSpecies(input.value.trim().toLowerCase()));}
function updatePreview(){const q=$("speciesSearch").value.trim().toLowerCase(),wrap=$("speciesPreview");wrap.innerHTML="";if(!q)return;state.pokemonIndex.filter((p)=>p.name.includes(q)||String(p.id).startsWith(q)).slice(0,20).forEach((p)=>{const btn=document.createElement("button");btn.className="preview-item";btn.type="button";btn.innerHTML=`<img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.id}.png" alt=""><span>#${String(p.id).padStart(4,"0")} ${formatName(p.name)}</span>`;btn.onclick=()=>{$("speciesSearch").value=p.name;wrap.innerHTML="";loadSpecies(String(p.id));};wrap.appendChild(btn);});}

async function loadSpecies(idOrName){if(!idOrName)return;const pokemon=await fetch(`https://pokeapi.co/api/v2/pokemon/${idOrName}`).then(r=>r.json());const species=await fetch(pokemon.species.url).then(r=>r.json());state.pokemon=pokemon;state.species=species;state.selectedLevel=[];state.selectedOther=[];state.selectedAbilities=[];state.selectedGender="";state.loyalty=0;state.xp=XP_TABLE[Number($("levelInput").value)||1]||0;state.imageCrop={zoom:100,x:50,y:50,src:""};$("sheetEmpty").hidden=true;$("sheetContent").hidden=false;$("basicControls").hidden=false;$("natureBlock").hidden=false;$("movesSection").hidden=false;buildGenderMenu();buildLoyalty();buildNature();buildBalls();await buildMovePools();renderMoveOptions();render();}

function buildNature(){const sel=$("natureSelect");sel.innerHTML="";NATURES.forEach((n)=>{const o=document.createElement("option");const plus=n.plus?`+2 ${STAT_LABELS[n.plus]}`:"neutra";const minus=n.minus?`-2 ${STAT_LABELS[n.minus]}`:"";o.value=n.name;o.textContent=`${n.pt} ${plus} ${minus}`;sel.appendChild(o);});sel.onchange=()=>{state.nature=NATURES.find((n)=>n.name===sel.value)||NATURES[0];render();};state.nature=NATURES[0];}
function buildLoyalty(){const wrap=$("loyaltyBlocks");wrap.innerHTML="";for(let i=1;i<=4;i++){const b=document.createElement("button");b.type="button";b.className="loyalty-block";b.textContent=i<=state.loyalty?"■":"□";b.onclick=()=>{state.loyalty=i;buildLoyalty();render();};wrap.appendChild(b);}if(state.loyalty===0){[...wrap.children].forEach((c)=>c.textContent="□");}}
function buildGenderMenu(){const menu=$("genderMenu"),btn=$("genderDropdownBtn");if(state.species?.gender_rate===-1){btn.textContent="Gênero: assexual";btn.disabled=true;menu.innerHTML="";return;}btn.disabled=false;menu.innerHTML="<button type='button' data-g='male'><img src='assets/icons/male.png' width='14'> Masculino</button><button type='button' data-g='female'><img src='assets/icons/female.png' width='14'> Feminino</button>";btn.onclick=()=>menu.classList.toggle("hidden");menu.querySelectorAll("button").forEach((b)=>b.onclick=()=>{state.selectedGender=b.dataset.g;btn.textContent=`Gênero: ${b.dataset.g==="male"?"Masculino":"Feminino"}`;menu.classList.add("hidden");render();});}
function buildBalls(){const wrap=$("pokeballGrid");wrap.innerHTML="";POKEBALLS.forEach((name)=>{const slug=name.toLowerCase().replace(/\s+/g,"-");const img=`assets/pokeball/${slug}.png`;const btn=document.createElement("button");btn.type="button";btn.className=`pokeball-item ${state.selectedBall===slug?"active":""}`;btn.innerHTML=`<img src="${img}" onerror="this.style.display='none'" alt="${name}"><span>${name}</span>`;btn.onclick=()=>{state.selectedBall=slug;buildBalls();render();};wrap.appendChild(btn);});}

function level(){return Math.max(1,Math.min(100,Number($("levelInput").value)||1));}
function isLegendary(){return Boolean(state.species?.is_legendary||state.species?.is_mythical);} 
function getBaseStats(){const raw={};state.pokemon.stats.forEach((s)=>raw[s.stat.name]=s.base_stat);return {hp:convertStat(raw.hp),atk:convertStat(raw.attack),def:convertStat(raw.defense),spatk:convertStat(raw["special-attack"]),spdef:convertStat(raw["special-defense"]),spd:convertStat(raw.speed)};}
function getFinalStats(base){const lv=level();const growth=Math.floor(lv/10);const out={};STAT_KEYS.forEach((k)=>{out[k]=base[k]+growth+(state.nature.plus===k?2:0)-(state.nature.minus===k?2:0);});return out;}
function captureChance(){if(state.mode!=="wild")return null;let c=100-Math.floor(level()/2);c+=0;const hpPct=100;if(hpPct>51)c-=30;const hasNext=Boolean(state.species?.evolves_from_species)||Boolean(state.species?.evolution_chain?.url);c+=hasNext?0:-10;if(state.shiny)c-=10;if(state.alpha)c-=20;if(isLegendary())c-=30;return Math.max(1,c);}

function renderTypeBlocks(el, types){el.innerHTML="";types.forEach((t)=>{const img=document.createElement("img");img.src=`assets/types block/${t}.png`;img.alt=t;img.onerror=()=>img.src=`assets/types/${t}.png`;el.appendChild(img);});}
async function renderRelations(){const data=await fetch("https://pokeapi.co/api/v2/type").then(r=>r.json());const map={};await Promise.all(data.results.map(async(t)=>{const d=await fetch(t.url).then(r=>r.json());map[t.name]=d.damage_relations;}));const mult={};Object.keys(map).forEach((k)=>mult[k]=1);state.pokemon.types.forEach((t)=>{map[t.type.name].double_damage_from.forEach((x)=>mult[x.name]*=2);map[t.type.name].half_damage_from.forEach((x)=>mult[x.name]*=.5);map[t.type.name].no_damage_from.forEach((x)=>mult[x.name]=0);});const put=(id,val)=>{const el=$(id);el.innerHTML="";Object.entries(mult).filter(([,m])=>m===val).forEach(([n])=>{const i=document.createElement("img");i.src=`assets/types block/${n}.png`;i.alt=n;i.onerror=()=>i.src=`assets/types/${n}.png`;el.appendChild(i);});};put("weaknesses",2);put("resistances",0.5);put("immunities",0);}

const pickVersion=(arr)=>[...arr].sort((a,b)=>VERSION_PRIORITY.indexOf(a.version_group.name)-VERSION_PRIORITY.indexOf(b.version_group.name))[0];
async function getMove(url){if(state.moveCache.has(url))return state.moveCache.get(url);const d=await fetch(url).then(r=>r.json());state.moveCache.set(url,d);return d;}
async function buildMovePools(){state.movesByLevel=[];state.movesByOther=[];for(const m of state.pokemon.moves){const v=pickVersion(m.version_group_details);if(!v)continue;const obj={name:m.move.name,url:m.move.url,level:v.level_learned_at,method:v.move_learn_method.name};if(v.move_learn_method.name==="level-up")state.movesByLevel.push(obj);else state.movesByOther.push(obj);}state.movesByLevel.sort((a,b)=>a.level-b.level);}
function renderMoveOptions(){const lv=level();const ls=$("levelMoveSelect"),ts=$("tmMoveSelect");ls.innerHTML="";ts.innerHTML="";state.movesByLevel.filter((m)=>m.level<=lv).forEach((m)=>ls.add(new Option(`Lv.${m.level} ${formatName(m.name)}`,m.name)));state.movesByOther.slice(0,300).forEach((m)=>ts.add(new Option(formatName(m.name),m.name)));}
function moveTypeColor(type){const c={fire:"#f08030",water:"#6890f0",grass:"#78c850",electric:"#f8d030",normal:"#a8a878",dark:"#705848",psychic:"#f85888",ice:"#98d8d8",fighting:"#c03028",poison:"#a040a0",ground:"#e0c068",flying:"#a890f0",bug:"#a8b820",rock:"#b8a038",ghost:"#705898",dragon:"#7038f8",steel:"#b8b8d0",fairy:"#ee99ac"};return c[type]||"#7bdc65";}
async function renderSelectedMoves(){const out=$("selectedMovesOutput");out.innerHTML="";for(const name of [...state.selectedLevel,...state.selectedOther]){const e=state.movesByLevel.find((m)=>m.name===name)||state.movesByOther.find((m)=>m.name===name);if(!e)continue;const d=await getMove(e.url);const li=document.createElement("li");const c=moveTypeColor(d.type.name);li.className="move-chip";li.style.background=`${c}22`;li.style.borderColor=`${c}88`;li.textContent=formatName(name);li.onclick=()=>openMoveModal(name);out.appendChild(li);}[$("levelMoveSlots"),$("tmMoveSlots")].forEach((el,i)=>{const arr=i===0?state.selectedLevel:state.selectedOther;el.innerHTML="";arr.forEach((m)=>{const li=document.createElement("li");li.textContent=formatName(m);li.onclick=()=>openMoveModal(m);el.appendChild(li);});});}

async function openMoveModal(moveName){const entry=[...state.movesByLevel,...state.movesByOther].find((m)=>m.name===moveName);if(!entry)return;const m=await getMove(entry.url);const c=moveTypeColor(m.type.name);const desc=m.effect_entries.find((x)=>x.language.name==="en")?.effect||"Sem descrição";$("moveModalTitle").textContent=formatName(moveName);$("moveDetailsBody").innerHTML=`<div class='move-modal-shell' style='border-color:${c}'><div class='move-details-title'>${formatName(moveName)}</div><p style='text-align:center'><img src='assets/types/${m.type.name}.png' width='24'> ${formatName(m.type.name)}</p><div class='move-details-grid'><div><img src='assets/icons/${m.damage_class.name}.png' width='24'><br>${formatName(m.damage_class.name)}</div><div>ACC<br><strong>${accuracyToRPG(m.accuracy||100)}</strong></div><div>PP<br><strong>${ppToRPG(m.pp||0)}</strong></div></div><p>Dano RPG: <strong>${powerToDamage(m.power)}</strong></p><section><h4>Descrição</h4><p>${desc}</p></section></div>`;$("moveDetailsModal").showModal();}

function renderAbilities(){const body=$("abilitiesModalBody");const limit=level()>=40?2:1;body.innerHTML=limit>1?"<p>Seu nível permite escolher uma segunda habilidade.</p>":"";state.pokemon.abilities.forEach((a)=>{const info=abilitiesData[a.ability.name]||{ptName:formatName(a.ability.name),name:formatName(a.ability.name),activation:"—",effect:"—"};const idx=state.selectedAbilities.indexOf(a.ability.name);const div=document.createElement("div");div.className=`ability-option ${idx===0?"selected-1":""} ${idx===1?"selected-2":""} ${a.is_hidden?"hidden-ability":""}`;div.innerHTML=`<strong>${info.ptName} (${info.name}) ${a.is_hidden?"<span style='color:#aaa'>(oculta)</span>":""}</strong><p>Ativação: ${info.activation}</p><p>Efeito: ${info.effect}</p>`;div.onclick=()=>{if(idx>=0){state.selectedAbilities.splice(idx,1);}else if(state.selectedAbilities.length<limit){state.selectedAbilities.push(a.ability.name);}else{state.selectedAbilities[limit-1]=a.ability.name;}renderAbilities();render();};body.appendChild(div);});}

function renderStatsCompact(base, final){const col=(title,keyGetter)=>`<div class='stats-col'><strong>${title}</strong><ul>${STAT_KEYS.map((k)=>`<li><span>${STAT_LABELS[k]}</span><span>${keyGetter(k)}</span></li>`).join("")}</ul></div>`;$("statsCompact").innerHTML=col("Basal",(k)=>base[k])+col("Pontos",()=>Math.floor(level()/10))+col("Final",(k)=>final[k]);}
function renderCapacities(final){const int=Math.min(4,Math.floor((final.spatk+final.spdef)/4));const str=Math.min(4,Math.floor((final.atk+final.def)/4));const mov=Math.min(4,Math.floor(final.spd/2));$("cap-int").textContent=int;$("cap-str").textContent=str;$("cap-mov").textContent=mov;$("cap-int-label").textContent=["Instintivo","Observador","Sagaz","Brilhante","Gênio"][int];$("cap-str-label").textContent=["Frágil","Subdesenvolvida","Treinada","Potente","Colossal"][str];$("cap-mov-label").textContent=["Lento","Ágil","Veloz","Relâmpago","Supersônico"][mov];}
function renderXP(){const lv=level();const min=XP_TABLE[lv],max=XP_TABLE[Math.min(100,lv+1)]||XP_TABLE[100];const pct=max===min?100:Math.max(0,Math.min(100,((state.xp-min)/(max-min))*100));$("xpBarFill").style.width=`${pct}%`;$("xpBarText").textContent=`XP ${state.xp} (${min} → ${max})`;}
function tryLevelUp(){let lv=level();let ups=[];while(lv<100&&state.xp>=XP_TABLE[lv+1]){lv++;ups.push(lv);}if(ups.length){$("levelInput").value=lv;const learned=state.movesByLevel.filter((m)=>ups.includes(m.level)).map((m)=>formatName(m.name));alert(`Subiu para nível ${lv}. Ganhou +1 ponto por nível.${learned.length?` Aprendeu: ${learned.join(", ")}`:""}`);renderMoveOptions();}}

function renderInfoTab(){const p=state.pokemon;const types=p.types.map((t)=>t.type.name);const female=state.species.gender_rate===-1?"assexual":`${state.species.gender_rate*12.5}%♀`;const loyaltyTxt=["Sem vínculo","Conhece você","Confia em você","Leal","Parceiro total"][state.loyalty]||"Sem vínculo";const loy=`${"■".repeat(state.loyalty)}${"□".repeat(4-state.loyalty)}`;$("infoContent").innerHTML=`<div class='info-row'><strong>Proporções:</strong> ${p.height/10}m | ${p.weight/10}kg</div><div class='info-row'><strong>Reprodução:</strong> ${female} | ${state.species.egg_groups.map((g)=>g.name).join(" | ")}</div><div class='info-row'><strong>Natureza:</strong> ${state.nature.pt} — ${state.nature.taste}</div><div class='info-row'><strong>Modo:</strong> ${state.mode==="wild"?"Selvagem":"Adestrado"}</div>${state.mode==="wild"?`<div class='info-row'><strong>Chance de captura:</strong> ${captureChance()}%</div><div class='info-row'><strong>XP dado:</strong> ${level()}</div>`:""}${state.mode!=="wild"?`<div class='info-row'><strong>Lealdade:</strong> ${loy}<br>${loyaltyTxt}</div>`:""}`;}

function render(){if(!state.pokemon)return;const p=state.pokemon,base=getBaseStats(),final=getFinalStats(base);const displayName=state.mode==="trained"&&$("nicknameInput").value.trim()?$("nicknameInput").value.trim():formatName(p.name);$("sheetName").textContent=displayName;$("sheetSpeciesSub").textContent=displayName!==formatName(p.name)?formatName(p.name):"";$("sheetDex").textContent=`#${String(p.id).padStart(4,"0")}`;$("sheetLevel").textContent=`Nv.${level()}`;$("sheetModeLabel").textContent=state.mode==="wild"?"Pokémon Selvagem":"Pokémon Adestrado";const art=state.imageCrop.src||p.sprites.other["official-artwork"].front_default||p.sprites.front_default;$("sheetSprite").src=art;$("sheetSprite").style.objectFit=state.imageCrop.src?"cover":"contain";if(state.imageCrop.src){$("sheetSprite").style.objectPosition=`${state.imageCrop.x}% ${state.imageCrop.y}%`;$("sheetSprite").style.transform=`scale(${state.imageCrop.zoom/100})`;}const t1=p.types[0]?.type.name||"normal";$("sheetImageButton").style.borderColor=moveTypeColor(t1);renderTypeBlocks($("sheetTypes"),p.types.map((t)=>t.type.name));$("sheetBadges").innerHTML=`${state.shiny?"<img class='badge-icon' src='assets/forms/shiny.png'>":""}${state.alpha?"<img class='badge-icon' src='assets/icons/alpha.png'>":""}`;$("sheetBallIcon").innerHTML=state.mode==="trained"&&state.selectedBall?`<img class='badge-icon' src='assets/pokeball/${state.selectedBall}.png' onerror="this.style.display='none'">`:"";renderStatsCompact(base,final);renderCapacities(final);$("hp1Fill").style.width="100%";$("hp2Fill").style.width="100%";$("hp1Text").textContent=`${final.hp*10}`;$("hp2Text").textContent=`${final.hp*5}`;renderXP();renderInfoTab();renderSelectedMoves();renderRelations();}

function setupEvents(){document.querySelectorAll("[data-close-modal]").forEach((b)=>b.onclick=()=>$(b.dataset.closeModal).close());$("openAbilitiesModalBtn").onclick=()=>{renderAbilities();$("abilitiesModal").showModal();};$("addLevelMoveBtn").onclick=()=>{const v=$("levelMoveSelect").value;if(!v||state.selectedLevel.includes(v)||state.selectedLevel.length>=4)return;state.selectedLevel.push(v);renderSelectedMoves();};$("addTmMoveBtn").onclick=()=>{const v=$("tmMoveSelect").value;if(!v||state.selectedOther.includes(v)||state.selectedOther.length>=4)return;state.selectedOther.push(v);renderSelectedMoves();};$("levelInput").addEventListener("input",()=>{renderMoveOptions();render();});$("nicknameInput").addEventListener("input",render);$("shinyToggle").onclick=()=>{state.shiny=!state.shiny;$("shinyToggle").classList.toggle("active",state.shiny);render();};$("alphaToggle").onclick=()=>{state.alpha=!state.alpha;$("alphaToggle").classList.toggle("active",state.alpha);render();};$("quickGenerateBtn").onclick=async()=>{const p=state.pokemonIndex[Math.floor(Math.random()*state.pokemonIndex.length)];await loadSpecies(String(p.id));$("levelInput").value=Math.floor(Math.random()*100)+1;render();};$("addXpBtn").onclick=()=>{state.xp+=Math.max(0,Number($("xpInput").value)||0);tryLevelUp();render();};$("copySheetBtn").onclick=async()=>{await navigator.clipboard.writeText(`${$("sheetDex").textContent} ${$("sheetName").textContent} ${$("sheetLevel").textContent}`);alert("Ficha copiada!");};$("copyMovesBtn").onclick=async()=>{await navigator.clipboard.writeText([...state.selectedLevel,...state.selectedOther].map(formatName).join("\n"));alert("Golpes copiados!");};$("savePokemonBtn").onclick=()=>saveCurrent();$("openStatsRadar").onclick=()=>openRadar("stats");$("openContestRadar").onclick=()=>openRadar("contest");$("sheetImageButton").onclick=()=>openImageModal();}

function openRadar(type){$("radarTitle").textContent=type==="stats"?"Radar de atributos basais":"Radar de concurso";$("radarBody").innerHTML=`<canvas id='radarCanvas' width='400' height='320'></canvas>${type==="contest"?`<p>Muffins disponíveis: ${state.muffins} <button id='mPlus'>+</button> <button id='mMinus'>-</button></p>`:""}`;if(typeof Chart!=="undefined"){const base=getFinalStats(getBaseStats());const labels=STAT_KEYS.map((k)=>STAT_LABELS[k]);const data=type==="stats"?STAT_KEYS.map((k)=>base[k]):STAT_KEYS.map((k)=>Math.min(3,Math.floor((base[k]+(state.muffins*10))/10)));new Chart($("radarCanvas"),{type:"radar",data:{labels,datasets:[{data,backgroundColor:"rgba(123,220,101,.2)",borderColor:"#7bdc65"}]},options:{plugins:{legend:{display:false}}}});}if(type==="contest"){$("mPlus").onclick=()=>{state.muffins=Math.min(5,state.muffins+1);openRadar("contest");};$("mMinus").onclick=()=>{state.muffins=Math.max(0,state.muffins-1);openRadar("contest");};}$("radarModal").showModal();}

function openImageModal(){if(state.mode!=="trained")return;$("cropBody").innerHTML=`<input id='imgUpload' type='file' accept='image/png,image/jpeg,image/gif'><label>Zoom <input id='cropZoom' type='range' min='80' max='180' value='${state.imageCrop.zoom}'></label><label>X <input id='cropX' type='range' min='0' max='100' value='${state.imageCrop.x}'></label><label>Y <input id='cropY' type='range' min='0' max='100' value='${state.imageCrop.y}'></label><div class='sheet-image-frame'><img id='cropPreview' src='${state.imageCrop.src||state.pokemon.sprites.other["official-artwork"].front_default}' style='object-fit:cover;object-position:${state.imageCrop.x}% ${state.imageCrop.y}%;transform:scale(${state.imageCrop.zoom/100})'></div><button id='saveCropBtn' type='button'>Salvar imagem</button>`;const sync=()=>{const z=Number($("cropZoom").value),x=Number($("cropX").value),y=Number($("cropY").value);$("cropPreview").style.objectPosition=`${x}% ${y}%`;$("cropPreview").style.transform=`scale(${z/100})`;};["cropZoom","cropX","cropY"].forEach((id)=>$(id).oninput=sync);$("imgUpload").onchange=()=>{const f=$("imgUpload").files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{$("cropPreview").src=String(reader.result);};reader.readAsDataURL(f);};$("saveCropBtn").onclick=()=>{state.imageCrop={zoom:Number($("cropZoom").value),x:Number($("cropX").value),y:Number($("cropY").value),src:$("cropPreview").src};$("imageCropModal").close();render();};$("imageCropModal").showModal();}

function getPayload(){return {pokemonId:state.pokemon.id,pokemonName:state.pokemon.name,nickname:$("nicknameInput").value.trim(),mode:state.mode,level:level(),xp:state.xp,shiny:state.shiny,alpha:state.alpha,nature:state.nature,abilities:[...state.selectedAbilities],moves:[...state.selectedLevel,...state.selectedOther],selectedBall:state.selectedBall,loyalty:state.loyalty,gender:state.selectedGender,imageCrop:state.imageCrop,sprite:state.imageCrop.src||state.pokemon.sprites.other["official-artwork"].front_default,dex:`#${String(state.pokemon.id).padStart(4,"0")}`};}
function saveCurrent(){const profile=getProfile();if(!profile){alert("Faça login para salvar.");return;}const saved=saveCreatedPokemon(getPayload());alert(`Salvo: ${saved.id}`);} 

async function loadFromQuery(){const id=new URLSearchParams(location.search).get("id");if(!id)return;const saved=getCreatedPokemonById(id);if(!saved)return;await loadSpecies(String(saved.pokemonId));$("nicknameInput").value=saved.nickname||"";$("levelInput").value=saved.level;state.mode=saved.mode;document.querySelector(`.mode-btn[data-mode='${saved.mode}']`)?.click();state.xp=saved.xp||XP_TABLE[saved.level]||0;state.shiny=Boolean(saved.shiny);state.alpha=Boolean(saved.alpha);state.nature=saved.nature||NATURES[0];$("natureSelect").value=state.nature.name;state.selectedAbilities=saved.abilities||[];state.selectedLevel=(saved.moves||[]).filter((m)=>state.movesByLevel.find((x)=>x.name===m)).slice(0,4);state.selectedOther=(saved.moves||[]).filter((m)=>state.movesByOther.find((x)=>x.name===m)).slice(0,4);state.selectedBall=saved.selectedBall||"";state.loyalty=saved.loyalty||0;state.selectedGender=saved.gender||"";state.imageCrop=saved.imageCrop||state.imageCrop;buildLoyalty();buildBalls();render();}

async function init(){setupMenu();initAuthUI();setupModes();setupSearch();setupEvents();await fetchIndex();await loadFromQuery();}
init();
